server:
  port: 8084
spring:
  application:
    name: ts-doctor-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # URI of our Auth Service. The resource server will fetch public keys from here to validate tokens.
          issuer-uri: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5432/doctors?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # A much more reasonable default
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Integration service URLs
services:
  auth-service:
    base-url: http://ts-auth-service
  user-service:
    base-url: http://ts-user-service

# Integration base URLs (used by integration services)
integration:
  user-service:
    base-url: http://ts-user-service/api/v1/users
  address-service:
    base-url: http://ts-address-service
  session-service:
    base-url: http://ts-session-service

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      auth-service:
              failure-rate-threshold: 50
              sliding-window-type: COUNT_BASED
              sliding-window-size: 10
              minimum-number-of-calls: 5
              wait-duration-in-open-state: 10s
              permitted-number-of-calls-in-half-open-state: 2
              register-health-indicator: true
      ts-user-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      ts-address-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      ts-session-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      auth-service:
        max-attempts: 3
        wait-duration: 500ms

      ts-user-service:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      ts-address-service:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      ts-session-service:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  timelimiter:
    instances:
      auth-service:
        timeout-duration: 20s
        cancel-running-future: true
      ts-user-service:
        timeoutDuration: 10s
      ts-address-service:
        timeoutDuration: 5s
      ts-session-service:
        timeoutDuration: 5s
internal:
  api:
    secret: "902ffc52f4ab670361e543008a5f8e86005edadfbc1df36f5cc375b433448aff"
